from __future__ import annotations

from collections.abc import Iterable, Iterator, Mapping, MutableMapping, Sequence
from typing import Any, Generic, TypeVar

_T = TypeVar("_T")
_Node = Tag | NavigableString
_AttrValue = str | AttributeValueList | None
_AttrRule = Any
_NameRule = str | bool | Iterable[str] | Any | None

__version__: str

class FeatureNotFound(ValueError): ...
class ParserRejectedMarkup(Exception): ...
class StopParsing(Exception): ...
class UnusualUsageWarning(UserWarning): ...
class GuessedAtParserWarning(UnusualUsageWarning): ...
class MarkupResemblesLocatorWarning(UnusualUsageWarning): ...
class AttributeResemblesVariableWarning(UnusualUsageWarning): ...
class XMLParsedAsHTMLWarning(UnusualUsageWarning): ...

class PageElement: ...

class ResultSet(list[_T], Generic[_T]):
    source: Any
    def __init__(
        self,
        source: Any = ...,
        result: Iterable[Any] = ...,
        source_factory: Any = ...,
    ) -> None: ...

class AttributeValueList(list[str]):
    def __init__(self, values: Iterable[Any] = ..., owner: Any = ..., key: str | None = ...) -> None: ...

class NavigableString(str):
    name: None
    parent: Tag | Soup | None
    parents: Sequence[Tag | Soup]
    string: NavigableString
    text: str
    next: _Node | None
    previous: _Node | None
    next_element: _Node | None
    previous_element: _Node | None
    next_sibling: _Node | None
    previous_sibling: _Node | None
    nextSibling: _Node | None
    previousSibling: _Node | None
    def __new__(cls, inner: object = "") -> NavigableString: ...
    def get_text(self, separator: str = "", strip: bool = False, *args: Any, **kwargs: Any) -> str: ...
    def getText(self, separator: str = "", strip: bool = False, *args: Any, **kwargs: Any) -> str: ...
    def find_next(self, name: _NameRule = None, attrs: Mapping[str, _AttrRule] | None = None, string: Any = None, **kwargs: Any) -> Tag | NavigableString | None: ...
    def find_all_next(self, name: _NameRule = None, attrs: Mapping[str, _AttrRule] | None = None, string: Any = None, limit: int | None = None, **kwargs: Any) -> ResultSet[_Node]: ...
    def find_previous(self, name: _NameRule = None, attrs: Mapping[str, _AttrRule] | None = None, string: Any = None, **kwargs: Any) -> Tag | NavigableString | None: ...
    def find_all_previous(self, name: _NameRule = None, attrs: Mapping[str, _AttrRule] | None = None, string: Any = None, limit: int | None = None, **kwargs: Any) -> ResultSet[_Node]: ...
    def find_parent(self, name: _NameRule = None, attrs: Mapping[str, _AttrRule] | None = None, string: Any = None, **kwargs: Any) -> Tag | Soup | None: ...
    def find_parents(self, name: _NameRule = None, attrs: Mapping[str, _AttrRule] | None = None, string: Any = None, limit: int | None = None, **kwargs: Any) -> ResultSet[Tag | Soup]: ...
    def find_next_sibling(self, name: _NameRule = None, attrs: Mapping[str, _AttrRule] | None = None, string: Any = None, **kwargs: Any) -> _Node | None: ...
    def find_next_siblings(self, name: _NameRule = None, attrs: Mapping[str, _AttrRule] | None = None, string: Any = None, limit: int | None = None, **kwargs: Any) -> ResultSet[_Node]: ...
    def find_previous_sibling(self, name: _NameRule = None, attrs: Mapping[str, _AttrRule] | None = None, string: Any = None, **kwargs: Any) -> _Node | None: ...
    def find_previous_siblings(self, name: _NameRule = None, attrs: Mapping[str, _AttrRule] | None = None, string: Any = None, limit: int | None = None, **kwargs: Any) -> ResultSet[_Node]: ...
    def extract(self) -> NavigableString: ...
    def decompose(self) -> None: ...
    def replace_with(self, *items: object) -> NavigableString: ...
    def insert_before(self, *items: object) -> list[_Node]: ...
    def insert_after(self, *items: object) -> list[_Node]: ...

class Comment(NavigableString): ...
class PreformattedString(NavigableString): ...
class CData(PreformattedString): ...
class Declaration(PreformattedString): ...
class Doctype(NavigableString): ...
class ProcessingInstruction(NavigableString): ...
class TemplateString(NavigableString): ...
class RubyTextString(TemplateString): ...
class RubyParenthesisString(TemplateString): ...
class Script(NavigableString): ...
class Stylesheet(NavigableString): ...

class _ElementApi:
    name: str
    text: str
    attrs: MutableMapping[str, _AttrValue]
    parent: Tag | Soup | None
    parents: Sequence[Tag | Soup]
    contents: Sequence[_Node]
    children: Sequence[_Node]
    descendants: Sequence[_Node]
    string: NavigableString | None
    strings: Sequence[NavigableString]
    stripped_strings: Sequence[str]
    next_sibling: _Node | None
    previous_sibling: _Node | None
    next_element: _Node | None
    previous_element: _Node | None
    css: CSS
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[_Node]: ...
    def __call__(self, name: _NameRule = None, attrs: Mapping[str, _AttrRule] | str | None = None, recursive: bool = True, string: Any = None, limit: int | None = None, **kwargs: Any) -> ResultSet[_Node]: ...
    def __getitem__(self, key: str) -> _AttrValue: ...
    def get(self, name: str, default: _T | None = None) -> _AttrValue | _T | None: ...
    def has_attr(self, name: str) -> bool: ...
    def get_attribute_list(self, name: str) -> list[str]: ...
    def get_text(self, separator: str = "", strip: bool = False, *args: Any, **kwargs: Any) -> str: ...
    def getText(self, separator: str = "", strip: bool = False, *args: Any, **kwargs: Any) -> str: ...
    def find(self, name: _NameRule = None, attrs: Mapping[str, _AttrRule] | str | None = None, recursive: bool = True, string: Any = None, **kwargs: Any) -> _Node | None: ...
    def find_all(self, name: _NameRule = None, attrs: Mapping[str, _AttrRule] | str | None = None, recursive: bool = True, string: Any = None, limit: int | None = None, **kwargs: Any) -> ResultSet[_Node]: ...
    def select(self, selector: str, namespaces: Any = None, limit: int = 0, **kwargs: Any) -> ResultSet[Tag]: ...
    def select_one(self, selector: str, namespaces: Any = None, **kwargs: Any) -> Tag | None: ...
    def append(self, item: object) -> _Node: ...
    def extend(self, items: Iterable[object]) -> list[_Node]: ...
    def insert(self, position: int, *new_children: object) -> list[_Node]: ...
    def clear(self) -> None: ...
    def extract(self) -> Tag: ...
    def decompose(self) -> None: ...
    def replace_with(self, *items: object) -> Tag: ...
    def insert_before(self, *items: object) -> list[_Node]: ...
    def insert_after(self, *items: object) -> list[_Node]: ...
    def unwrap(self) -> Tag: ...
    def decode_contents(self, indent_level: int | None = None, eventual_encoding: str = "utf-8", formatter: Any = "minimal") -> str: ...
    def encode_contents(self, indent_level: int | None = None, encoding: str = "utf-8", formatter: Any = "minimal") -> bytes: ...
    def decode(self, indent_level: int | None = None, eventual_encoding: str = "utf-8", formatter: Any = "minimal", iterator: Any = None) -> str: ...
    def encode(self, encoding: str = "utf-8", indent_level: int | None = None, formatter: Any = "minimal", errors: str = "xmlcharrefreplace") -> bytes: ...
    def prettify(self, encoding: str | None = None, formatter: Any = "minimal") -> str | bytes: ...

class Tag(_ElementApi): ...

class Soup(_ElementApi):
    title: Tag | None
    original_encoding: str | None
    declared_html_encoding: str | None
    contains_replacement_characters: bool
    def __init__(
        self,
        markup: str | bytes | Any = "",
        features: str | Iterable[str] | None = None,
        builder: Any = None,
        parse_only: SoupStrainer | None = None,
        from_encoding: str | None = None,
        exclude_encodings: Iterable[str] | None = None,
        element_classes: Mapping[type[Any], type[Any]] | None = None,
        **kwargs: Any,
    ) -> None: ...
    def new_tag(self, name: str, namespace: Any = None, nsprefix: Any = None, attrs: Mapping[str, Any] | None = None, sourceline: Any = None, sourcepos: Any = None, string: Any = None, **kwargs: Any) -> Tag: ...
    def new_string(self, s: object, subclass: type[NavigableString] | None = None) -> NavigableString: ...

BeautifulSoup = Soup
BeautifulStoneSoup = Soup

class CSS:
    api: Soup | Tag
    def __init__(self, owner: Soup | Tag) -> None: ...
    def select(self, select: str, namespaces: Any = None, limit: int = 0, flags: int = 0, **kwargs: Any) -> ResultSet[Tag]: ...
    def select_one(self, select: str, namespaces: Any = None, flags: int = 0, **kwargs: Any) -> Tag | None: ...
    def iselect(self, select: str, namespaces: Any = None, limit: int = 0, flags: int = 0, **kwargs: Any) -> Iterator[Tag]: ...
    def filter(self, select: str, namespaces: Any = None, flags: int = 0, **kwargs: Any) -> ResultSet[Tag]: ...
    def match(self, select: str, namespaces: Any = None, flags: int = 0, **kwargs: Any) -> bool: ...
    def closest(self, select: str, namespaces: Any = None, flags: int = 0, **kwargs: Any) -> Tag | None: ...
    def escape(self, ident: object) -> str: ...

class ElementFilter:
    includes_everything: bool
    excludes_everything: bool
    def __init__(self, match_function: Any = None) -> None: ...
    def match(self, element: object, _known_rules: bool = False) -> bool: ...
    def filter(self, generator: Iterable[_T]) -> Iterator[_T]: ...
    def find(self, generator: Iterable[_T]) -> _T | None: ...
    def find_all(self, generator: Iterable[_T], limit: int | None = None) -> ResultSet[_T]: ...

class SoupStrainer(ElementFilter):
    name: Any
    attrs: dict[str, Any]
    string: Any
    text: Any
    def __init__(self, name: Any = None, attrs: Mapping[str, Any] | str | None = None, string: Any = None, **kwargs: Any) -> None: ...
    def matches_tag(self, tag: Tag) -> bool: ...
    def search(self, element: object) -> object | None: ...

class HTMLFormatter:
    name: str | None
    def __init__(self, name: str | None = "minimal") -> None: ...
    def substitute(self, value: object) -> str: ...

Formatter = HTMLFormatter

class UnicodeDammit:
    unicode_markup: str
    original_encoding: str | None
    contains_replacement_characters: bool
    def __init__(
        self,
        markup: str | bytes,
        known_definite_encodings: Iterable[str] | None = None,
        smart_quotes_to: str | None = None,
        is_html: bool = False,
        exclude_encodings: Iterable[str] | None = None,
        user_encodings: Iterable[str] | None = None,
        override_encodings: Iterable[str] | None = None,
    ) -> None: ...
    @classmethod
    def detwingle(cls, in_bytes: bytes, main_encoding: str = "utf8", embedded_encoding: str = "windows-1252") -> bytes: ...

class HTMLParserTreeBuilder: ...
class TreeBuilder: ...
builder_registry: Any

__all__: list[str]
